export interface Country {
  code: string;
  name: string;
  tier: number; // 1: Easy, 2: Medium, 3: Hard, 4: Expert
  region: string;
  category: 'National' | 'US-State' | 'India-State' | 'Danish-Kommune' | 'Swedish-Lan' | 'German-County' | 'Swiss-Canton' | 'Commonwealth' | 'World-Capitals' | 'Language-Guess';
  fact?: string;
  imageUrl?: string; // For World Capitals
  audioUrl?: string; // For Language Guess
  population?: number; // For Population game mode
  capital?: string; // For Capital to Flag mode
}

export const COUNTRIES: Country[] = [
  // National Flags (Existing)
  { code: 'us', name: 'United States', tier: 1, region: 'Americas', category: 'National', fact: "The 50 stars represent the 50 states.", population: 331000000, capital: 'Washington D.C.' },
  { code: 'gb', name: 'United Kingdom', tier: 1, region: 'Europe', category: 'National', fact: "The flag is known as the Union Jack.", population: 67000000, capital: 'London' },
  { code: 'fr', name: 'France', tier: 1, region: 'Europe', category: 'National', fact: "The tricolor design inspired many other flags.", population: 67000000, capital: 'Paris' },
  { code: 'de', name: 'Germany', tier: 1, region: 'Europe', category: 'National', fact: "The colors represent the 1848 revolutions.", population: 83000000, capital: 'Berlin' },
  { code: 'jp', name: 'Japan', tier: 1, region: 'Asia', category: 'National', fact: "The red circle represents the sun.", population: 125000000, capital: 'Tokyo' },
  { code: 'cn', name: 'China', tier: 1, region: 'Asia', category: 'National', fact: "The large star represents the Communist Party.", population: 1411000000, capital: 'Beijing' },
  { code: 'ca', name: 'Canada', tier: 1, region: 'Americas', category: 'National', fact: "The maple leaf became official in 1965.", population: 38000000, capital: 'Ottawa' },
  { code: 'au', name: 'Australia', tier: 1, region: 'Oceania', category: 'National', fact: "Features the Southern Cross constellation.", population: 25000000, capital: 'Canberra' },
  { code: 'br', name: 'Brazil', tier: 1, region: 'Americas', category: 'National', fact: "The globe shows the sky over Rio in 1889.", population: 212000000, capital: 'Brasília' },
  { code: 'it', name: 'Italy', tier: 1, region: 'Europe', category: 'National', fact: "Green represents the plains and hills.", population: 59000000, capital: 'Rome' },
  { code: 'es', name: 'Spain', tier: 1, region: 'Europe', category: 'National', fact: "The coat of arms features the Pillars of Hercules.", population: 47000000, capital: 'Madrid' },
  { code: 'in', name: 'India', tier: 1, region: 'Asia', category: 'National', fact: "The wheel is the Ashoka Chakra.", population: 1380000000, capital: 'New Delhi' },
  { code: 'ru', name: 'Russia', tier: 1, region: 'Europe', category: 'National', fact: "The white, blue, and red are pan-Slavic colors.", population: 144000000, capital: 'Moscow' },
  { code: 'mx', name: 'Mexico', tier: 1, region: 'Americas', category: 'National', fact: "Shows an eagle perched on a cactus.", population: 128000000, capital: 'Mexico City' },
  { code: 'kr', name: 'South Korea', tier: 1, region: 'Asia', category: 'National', fact: "The center symbol represents Yin and Yang.", population: 51000000, capital: 'Seoul' },
  { code: 'se', name: 'Sweden', tier: 1, region: 'Europe', category: 'National', fact: "The yellow cross represents the sun.", population: 10000000, capital: 'Stockholm' },
  { code: 'no', name: 'Norway', tier: 1, region: 'Europe', category: 'National', fact: "The cross is a symbol of Christianity.", population: 54000000, capital: 'Oslo' },
  { code: 'dk', name: 'Denmark', tier: 1, region: 'Europe', category: 'National', fact: "The oldest continuously used national flag.", population: 5800000, capital: 'Copenhagen' },
  { code: 'fi', name: 'Finland', tier: 1, region: 'Europe', category: 'National', fact: "The blue cross represents the thousands of lakes.", population: 5500000, capital: 'Helsinki' },
  { code: 'ch', name: 'Switzerland', tier: 1, region: 'Europe', category: 'National', fact: "One of only two square national flags.", population: 8600000, capital: 'Bern' },
  { code: 'ar', name: 'Argentina', tier: 2, region: 'Americas', category: 'National', fact: "The Sun of May represents the Incan sun god.", population: 45000000 },
  { code: 'nl', name: 'Netherlands', tier: 2, region: 'Europe', category: 'National', fact: "The oldest tricolor flag still in use.", population: 17000000 },
  { code: 'be', name: 'Belgium', tier: 2, region: 'Europe', category: 'National', fact: "The colors are from the Duchy of Brabant.", population: 11500000 },
  { code: 'at', name: 'Austria', tier: 2, region: 'Europe', category: 'National', fact: "Legend says the design came from a bloody tunic.", population: 8900000 },
  { code: 'pt', name: 'Portugal', tier: 2, region: 'Europe', category: 'National', fact: "The green represents hope for the future.", population: 10300000 },
  { code: 'gr', name: 'Greece', tier: 2, region: 'Europe', category: 'National', fact: "The nine stripes represent the nine muses.", population: 10700000 },
  { code: 'tr', name: 'Turkey', tier: 2, region: 'Asia', category: 'National', fact: "The crescent and star are ancient symbols.", population: 84000000 },
  { code: 'eg', name: 'Egypt', tier: 2, region: 'Africa', category: 'National', fact: "Features the Eagle of Saladin.", population: 102000000 },
  { code: 'za', name: 'South Africa', tier: 2, region: 'Africa', category: 'National', fact: "Adopted after the end of apartheid.", population: 59000000 },
  { code: 'th', name: 'Thailand', tier: 2, region: 'Asia', category: 'National', fact: "The blue represents the monarchy.", population: 69000000 },
  { code: 'vn', name: 'Vietnam', tier: 2, region: 'Asia', category: 'National', fact: "The five points of the star represent five classes.", population: 97000000 },
  { code: 'id', name: 'Indonesia', tier: 2, region: 'Asia', category: 'National', fact: "Red represents courage, white represents purity.", population: 273000000 },
  { code: 'my', name: 'Malaysia', tier: 2, region: 'Asia', category: 'National', fact: "The 14 stripes represent the 13 states and federal gov.", population: 32000000 },
  { code: 'ph', name: 'Philippines', tier: 2, region: 'Asia', category: 'National', fact: "The sun's rays represent the first eight provinces.", population: 109000000 },
  { code: 'pl', name: 'Poland', tier: 2, region: 'Europe', category: 'National', fact: "The white represents peace, red represents blood.", population: 38000000 },
  { code: 'ie', name: 'Ireland', tier: 2, region: 'Europe', category: 'National', fact: "Green represents Catholics, orange represents Protestants.", population: 4900000 },
  { code: 'nz', name: 'New Zealand', tier: 2, region: 'Oceania', category: 'National', fact: "Features the Southern Cross with red stars.", population: 5000000 },
  { code: 'cl', name: 'Chile', tier: 2, region: 'Americas', category: 'National', fact: "Known as 'La Estrella Solitaria' (The Lone Star).", population: 19000000 },
  { code: 'co', name: 'Colombia', tier: 2, region: 'Americas', category: 'National', fact: "Yellow represents the wealth of the land.", population: 50000000 },
  { code: 'pe', name: 'Peru', tier: 2, region: 'Americas', category: 'National', fact: "The coat of arms features a vicuña and a cinchona tree.", population: 33000000 },
  { code: 'af', name: 'Afghanistan', tier: 4, region: 'Asia', category: 'National', fact: "The flag features the national emblem with a mosque.", population: 38900000 },
  { code: 'al', name: 'Albania', tier: 3, region: 'Europe', category: 'National', fact: "Features a double-headed eagle.", population: 2800000 },
  { code: 'dz', name: 'Algeria', tier: 2, region: 'Africa', category: 'National', fact: "The star and crescent are symbols of Islam.", population: 43000000 },
  { code: 'ad', name: 'Andorra', tier: 4, region: 'Europe', category: 'National', fact: "Features the motto 'Virtus Unita Fortior'.", population: 77000 },
  { code: 'ao', name: 'Angola', tier: 3, region: 'Africa', category: 'National', fact: "Features a machete and a cogwheel.", population: 32800000 },
  { code: 'ag', name: 'Antigua and Barbuda', tier: 4, region: 'Americas', category: 'National', fact: "The rising sun symbolizes a new era.", population: 98000 },
  { code: 'am', name: 'Armenia', tier: 3, region: 'Asia', category: 'National', fact: "The colors represent the Armenian Highland.", population: 2900000 },
  { code: 'az', name: 'Azerbaijan', tier: 3, region: 'Asia', category: 'National', fact: "Features an eight-pointed star.", population: 10100000 },
  { code: 'bs', name: 'Bahamas', tier: 4, region: 'Americas', category: 'National', fact: "The black triangle represents the people.", population: 393000 },
  { code: 'bh', name: 'Bahrain', tier: 4, region: 'Asia', category: 'National', fact: "The five points represent the five pillars of Islam.", population: 1700000 },
  { code: 'bb', name: 'Barbados', tier: 4, region: 'Americas', category: 'National', fact: "Features a broken trident.", population: 287000 },
  { code: 'by', name: 'Belarus', tier: 3, region: 'Europe', category: 'National', fact: "Features a traditional decorative pattern.", population: 9400000 },
  { code: 'bz', name: 'Belize', tier: 4, region: 'Americas', category: 'National', fact: "The only national flag with humans as a major element.", population: 397000 },
  { code: 'bj', name: 'Benin', tier: 4, region: 'Africa', category: 'National', fact: "The colors are the Pan-African colors.", population: 12100000 },
  { code: 'bo', name: 'Bolivia', tier: 3, region: 'Americas', category: 'National', fact: "Features the national coat of arms.", population: 11600000 },
  { code: 'ba', name: 'Bosnia and Herzegovina', tier: 3, region: 'Europe', category: 'National', fact: "The triangle represents the three main ethnic groups.", population: 3300000 },
  { code: 'bw', name: 'Botswana', tier: 3, region: 'Africa', category: 'National', fact: "The colors represent water and the zebra.", population: 2300000 },
  { code: 'bn', name: 'Brunei', tier: 4, region: 'Asia', category: 'National', fact: "Features the national emblem.", population: 437000 },
  { code: 'bf', name: 'Burkina Faso', tier: 4, region: 'Africa', category: 'National', fact: "Features a yellow star on a red and green field.", population: 20900000 },
  { code: 'bi', name: 'Burundi', tier: 4, region: 'Africa', category: 'National', fact: "The three stars represent 'Unity, Work, Progress'.", population: 11800000 },
  { code: 'kh', name: 'Cambodia', tier: 3, region: 'Asia', category: 'National', fact: "Features Angkor Wat.", population: 16700000 },
  { code: 'cm', name: 'Cameroon', tier: 3, region: 'Africa', category: 'National', fact: "Features a 'star of unity'.", population: 26500000 },
  { code: 'cv', name: 'Cabo Verde', tier: 4, region: 'Africa', category: 'National', fact: "The 10 stars represent the 10 islands.", population: 555000 },
  { code: 'cf', name: 'Central African Republic', tier: 4, region: 'Africa', category: 'National', fact: "Combines French and Pan-African colors.", population: 4800000 },
  { code: 'td', name: 'Chad', tier: 4, region: 'Africa', category: 'National', fact: "Identical to the flag of Romania.", population: 16400000 },
  { code: 'km', name: 'Comoros', tier: 4, region: 'Africa', category: 'National', fact: "The four stars represent the four islands.", population: 869000 },
  { code: 'cg', name: 'Congo', tier: 4, region: 'Africa', category: 'National', fact: "Features a diagonal yellow stripe.", population: 5500000 },
  { code: 'cd', name: 'DR Congo', tier: 4, region: 'Africa', category: 'National', fact: "Features a large yellow star.", population: 89500000 },
  { code: 'cr', name: 'Costa Rica', tier: 3, region: 'Americas', category: 'National', fact: "Inspired by the French Tricolore.", population: 5100000 },
  { code: 'ci', name: 'Côte d\'Ivoire', tier: 3, region: 'Africa', category: 'National', fact: "Similar to the flag of Ireland, but reversed.", population: 26300000 },
  { code: 'cy', name: 'Cyprus', tier: 3, region: 'Europe', category: 'National', fact: "Features the map of the island.", population: 1200000 },
  { code: 'dj', name: 'Djibouti', tier: 4, region: 'Africa', category: 'National', fact: "The red star represents unity.", population: 988000 },
  { code: 'dm', name: 'Dominica', tier: 4, region: 'Americas', category: 'National', fact: "Features a Sisserou parrot.", population: 72000 },
  { code: 'do', name: 'Dominican Republic', tier: 3, region: 'Americas', category: 'National', fact: "The only national flag with a Bible on it.", population: 10800000 },
  { code: 'ec', name: 'Ecuador', tier: 3, region: 'Americas', category: 'National', fact: "Features an Andean condor.", population: 17600000 },
  { code: 'sv', name: 'El Salvador', tier: 3, region: 'Americas', category: 'National', fact: "Features the national coat of arms.", population: 6500000 },
  { code: 'gq', name: 'Equatorial Guinea', tier: 4, region: 'Africa', category: 'National', fact: "Features a silk-cotton tree.", population: 1400000 },
  { code: 'er', name: 'Eritrea', tier: 4, region: 'Africa', category: 'National', fact: "Features an olive branch wreath.", population: 3500000 },
  { code: 'sz', name: 'Eswatini', tier: 4, region: 'Africa', category: 'National', fact: "Features a Nguni shield.", population: 1160000 },
  { code: 'fj', name: 'Fiji', tier: 3, region: 'Oceania', category: 'National', fact: "Features the Union Jack and a shield.", population: 896000 },
  { code: 'ga', name: 'Gabon', tier: 4, region: 'Africa', category: 'National', fact: "Green represents forests, yellow represents the sun.", population: 2200000 },
  { code: 'gm', name: 'Gambia', tier: 4, region: 'Africa', category: 'National', fact: "The blue stripe represents the Gambia River.", population: 2400000 },
  { code: 'ge', name: 'Georgia', tier: 3, region: 'Europe', category: 'National', fact: "Features five crosses.", population: 3700000 },
  { code: 'gd', name: 'Grenada', tier: 4, region: 'Americas', category: 'National', fact: "Features a nutmeg clove.", population: 112000 },
  { code: 'gt', name: 'Guatemala', tier: 3, region: 'Americas', category: 'National', fact: "Features the Resplendent Quetzal.", population: 17900000 },
  { code: 'gn', name: 'Guinea', tier: 4, region: 'Africa', category: 'National', fact: "The colors are the Pan-African colors.", population: 13100000 },
  { code: 'gw', name: 'Guinea-Bissau', tier: 4, region: 'Africa', category: 'National', fact: "Features the black star of Africa.", population: 1960000 },
  { code: 'gy', name: 'Guyana', tier: 4, region: 'Americas', category: 'National', fact: "Known as 'The Golden Arrowhead'.", population: 786000 },
  { code: 'ht', name: 'Haiti', tier: 3, region: 'Americas', category: 'National', fact: "Features the national coat of arms.", population: 11400000 },
  { code: 'hn', name: 'Honduras', tier: 3, region: 'Americas', category: 'National', fact: "The five stars represent the former Central American Federation.", population: 9900000 },
  { code: 'iq', name: 'Iraq', tier: 2, region: 'Asia', category: 'National', fact: "Features the Takbir in Kufic script.", population: 40200000 },
  { code: 'jo', name: 'Jordan', tier: 3, region: 'Asia', category: 'National', fact: "Features a seven-pointed star.", population: 10200000 },
  { code: 'kz', name: 'Kazakhstan', tier: 3, region: 'Asia', category: 'National', fact: "Features a steppe eagle and a sun.", population: 18700000 },
  { code: 'ki', name: 'Kiribati', tier: 4, region: 'Oceania', category: 'National', fact: "Features a frigatebird over a rising sun.", population: 119000 },
  { code: 'kw', name: 'Kuwait', tier: 3, region: 'Asia', category: 'National', fact: "The colors represent blood, purity, and fertile land.", population: 4200000 },
  { code: 'kg', name: 'Kyrgyzstan', tier: 4, region: 'Asia', category: 'National', fact: "Features a sun with 40 rays.", population: 6500000 },
  { code: 'la', name: 'Laos', tier: 4, region: 'Asia', category: 'National', fact: "Features a white moon over the Mekong River.", population: 7200000 },
  { code: 'lb', name: 'Lebanon', tier: 3, region: 'Asia', category: 'National', fact: "Features a Lebanon Cedar.", population: 6800000 },
  { code: 'ls', name: 'Lesotho', tier: 4, region: 'Africa', category: 'National', fact: "Features a Basotho hat.", population: 2100000 },
  { code: 'lr', name: 'Liberia', tier: 3, region: 'Africa', category: 'National', fact: "Modeled after the flag of the United States.", population: 5000000 },
  { code: 'ly', name: 'Libya', tier: 3, region: 'Africa', category: 'National', fact: "Features a white star and crescent.", population: 6800000 },
  { code: 'li', name: 'Liechtenstein', tier: 4, region: 'Europe', category: 'National', fact: "The crown was added to distinguish it from Haiti.", population: 38000 },
  { code: 'lu', name: 'Luxembourg', tier: 3, region: 'Europe', category: 'National', fact: "Very similar to the flag of the Netherlands.", population: 632000 },
  { code: 'mg', name: 'Madagascar', tier: 3, region: 'Africa', category: 'National', fact: "White represents purity, red represents sovereignty.", population: 27600000 },
  { code: 'mw', name: 'Malawi', tier: 4, region: 'Africa', category: 'National', fact: "Features a rising sun.", population: 19100000 },
  { code: 'mv', name: 'Maldives', tier: 4, region: 'Asia', category: 'National', fact: "Features a white crescent on a green field.", population: 540000 },
  { code: 'ml', name: 'Mali', tier: 4, region: 'Africa', category: 'National', fact: "The colors are the Pan-African colors.", population: 20200000 },
  { code: 'mt', name: 'Malta', tier: 3, region: 'Europe', category: 'National', fact: "Features the George Cross.", population: 514000 },
  { code: 'mh', name: 'Marshall Islands', tier: 4, region: 'Oceania', category: 'National', fact: "The star has 24 points.", population: 59000 },
  { code: 'mr', name: 'Mauritania', tier: 4, region: 'Africa', category: 'National', fact: "Features a crescent and a star.", population: 4600000 },
  { code: 'mu', name: 'Mauritius', tier: 4, region: 'Africa', category: 'National', fact: "Known as the 'Four Bands'.", population: 1200000 },
  { code: 'fm', name: 'Micronesia', tier: 4, region: 'Oceania', category: 'National', fact: "The four stars represent the four states.", population: 115000 },
  { code: 'md', name: 'Moldova', tier: 3, region: 'Europe', category: 'National', fact: "Features the national coat of arms.", population: 2600000 },
  { code: 'mc', name: 'Monaco', tier: 4, region: 'Europe', category: 'National', fact: "Identical to the flag of Indonesia.", population: 39000 },
  { code: 'mn', name: 'Mongolia', tier: 3, region: 'Asia', category: 'National', fact: "Features the Soyombo symbol.", population: 3200000 },
  { code: 'me', name: 'Montenegro', tier: 3, region: 'Europe', category: 'National', fact: "Features a double-headed eagle.", population: 622000 },
  { code: 'mz', name: 'Mozambique', tier: 3, region: 'Africa', category: 'National', fact: "The only national flag to feature a modern assault rifle.", population: 31200000 },
  { code: 'mm', name: 'Myanmar', tier: 3, region: 'Asia', category: 'National', fact: "Features a large white star.", population: 54400000 },
  { code: 'na', name: 'Namibia', tier: 3, region: 'Africa', category: 'National', fact: "Features a sun with 12 rays.", population: 2500000 },
  { code: 'nr', name: 'Nauru', tier: 4, region: 'Oceania', category: 'National', fact: "The star represents the 12 original tribes.", population: 10000 },
  { code: 'ni', name: 'Nicaragua', tier: 3, region: 'Americas', category: 'National', fact: "Features the national coat of arms.", population: 6600000 },
  { code: 'ne', name: 'Niger', tier: 4, region: 'Africa', category: 'National', fact: "The orange circle represents the sun.", population: 24200000 },
  { code: 'mk', name: 'North Macedonia', tier: 3, region: 'Europe', category: 'National', fact: "Features a stylized yellow sun.", population: 2000000 },
  { code: 'om', name: 'Oman', tier: 3, region: 'Asia', category: 'National', fact: "Features the national emblem (Khanjar).", population: 5100000 },
  { code: 'pw', name: 'Palau', tier: 4, region: 'Oceania', category: 'National', fact: "The yellow circle represents the moon.", population: 18000 },
  { code: 'pa', name: 'Panama', tier: 3, region: 'Americas', category: 'National', fact: "The stars represent the political parties.", population: 4300000 },
  { code: 'pg', name: 'Papua New Guinea', tier: 3, region: 'Oceania', category: 'National', fact: "Features a bird of paradise.", population: 8900000 },
  { code: 'py', name: 'Paraguay', tier: 3, region: 'Americas', category: 'National', fact: "The only national flag with different emblems on each side.", population: 7100000 },
  { code: 'qa', name: 'Qatar', tier: 3, region: 'Asia', category: 'National', fact: "The only national flag with a width more than twice its height.", population: 2800000 },
  { code: 'rw', name: 'Rwanda', tier: 4, region: 'Africa', category: 'National', fact: "Features a yellow sun.", population: 12900000 },
  { code: 'kn', name: 'Saint Kitts and Nevis', tier: 4, region: 'Americas', category: 'National', fact: "The two stars represent hope and liberty.", population: 53000 },
  { code: 'lc', name: 'Saint Lucia', tier: 4, region: 'Americas', category: 'National', fact: "Features the Pitons.", population: 183000 },
  { code: 'vc', name: 'Saint Vincent and the Grenadines', tier: 4, region: 'Americas', category: 'National', fact: "Features three green diamonds.", population: 110000 },
  { code: 'ws', name: 'Samoa', tier: 4, region: 'Oceania', category: 'National', fact: "Features the Southern Cross.", population: 198000 },
  { code: 'sm', name: 'San Marino', tier: 4, region: 'Europe', category: 'National', fact: "Features the national coat of arms.", population: 34000 },
  { code: 'st', name: 'Sao Tome and Principe', tier: 4, region: 'Africa', category: 'National', fact: "The two stars represent the two islands.", population: 219000 },
  { code: 'sn', name: 'Senegal', tier: 3, region: 'Africa', category: 'National', fact: "Features a green star.", population: 16700000 },
  { code: 'sc', name: 'Seychelles', tier: 4, region: 'Africa', category: 'National', fact: "Features five oblique bands.", population: 98000 },
  { code: 'sl', name: 'Sierra Leone', tier: 4, region: 'Africa', category: 'National', fact: "Green represents agriculture, blue represents the sea.", population: 7900000 },
  { code: 'sg', name: 'Singapore', tier: 2, region: 'Asia', category: 'National', fact: "Features a crescent moon and five stars.", population: 5800000 },
  { code: 'si', name: 'Slovenia', tier: 3, region: 'Europe', category: 'National', fact: "Features Mount Triglav.", population: 2100000 },
  { code: 'sb', name: 'Solomon Islands', tier: 4, region: 'Oceania', category: 'National', fact: "The five stars represent the five main island groups.", population: 686000 },
  { code: 'so', name: 'Somalia', tier: 3, region: 'Africa', category: 'National', fact: "Features a five-pointed 'Star of Unity'.", population: 15800000 },
  { code: 'ss', name: 'South Sudan', tier: 4, region: 'Africa', category: 'National', fact: "Features a yellow star on a blue triangle.", population: 11100000 },
  { code: 'lk', name: 'Sri Lanka', tier: 3, region: 'Asia', category: 'National', fact: "Features a lion holding a sword.", population: 21900000 },
  { code: 'sd', name: 'Sudan', tier: 3, region: 'Africa', category: 'National', fact: "Features a green triangle.", population: 43800000 },
  { code: 'sr', name: 'Suriname', tier: 4, region: 'Americas', category: 'National', fact: "Features a yellow star representing unity.", population: 586000 },
  { code: 'sy', name: 'Syria', tier: 3, region: 'Asia', category: 'National', fact: "Features two green stars.", population: 17500000 },
  { code: 'tj', name: 'Tajikistan', tier: 4, region: 'Asia', category: 'National', fact: "Features a crown and seven stars.", population: 9500000 },
  { code: 'tz', name: 'Tanzania', tier: 3, region: 'Africa', category: 'National', fact: "Features a diagonal black band.", population: 59700000 },
  { code: 'tl', name: 'Timor-Leste', tier: 4, region: 'Asia', category: 'National', fact: "Features a white star on a black triangle.", population: 1300000 },
  { code: 'tg', name: 'Togo', tier: 4, region: 'Africa', category: 'National', fact: "Features a white star on a red square.", population: 8200000 },
  { code: 'to', name: 'Tonga', tier: 4, region: 'Oceania', category: 'National', fact: "Features a red cross on a white square.", population: 105000 },
  { code: 'tt', name: 'Trinidad and Tobago', tier: 3, region: 'Americas', category: 'National', fact: "Features a diagonal black stripe.", population: 1400000 },
  { code: 'tn', name: 'Tunisia', tier: 3, region: 'Africa', category: 'National', fact: "Features a red crescent and star.", population: 11800000 },
  { code: 'tm', name: 'Turkmenistan', tier: 4, region: 'Asia', category: 'National', fact: "The most detailed national flag in the world.", population: 6000000 },
  { code: 'tv', name: 'Tuvalu', tier: 4, region: 'Oceania', category: 'National', fact: "The nine stars represent the nine islands.", population: 11000 },
  { code: 'ug', name: 'Uganda', tier: 3, region: 'Africa', category: 'National', fact: "Features a grey crowned crane.", population: 45700000 },
  { code: 'ae', name: 'United Arab Emirates', tier: 2, region: 'Asia', category: 'National', fact: "The colors represent Arab unity.", population: 9800000 },
  { code: 'uz', name: 'Uzbekistan', tier: 3, region: 'Asia', category: 'National', fact: "Features 12 stars and a crescent.", population: 34200000 },
  { code: 'vu', name: 'Vanuatu', tier: 4, region: 'Oceania', category: 'National', fact: "Features a boar's tusk.", population: 307000 },
  { code: 'ye', name: 'Yemen', tier: 3, region: 'Asia', category: 'National', fact: "The colors represent the Arab Liberation flag.", population: 29800000 },
  { code: 'zm', name: 'Zambia', tier: 4, region: 'Africa', category: 'National', fact: "Features an orange eagle.", population: 18300000 },
  { code: 'zw', name: 'Zimbabwe', tier: 3, region: 'Africa', category: 'National', fact: "Features the Great Zimbabwe Bird.", population: 14800000 },
  { code: 'va', name: 'Vatican City', tier: 4, region: 'Europe', category: 'National', fact: "The smallest independent state in the world.", population: 800 },
  { code: 'ua', name: 'Ukraine', tier: 2, region: 'Europe', category: 'National', fact: "Blue represents the sky, yellow represents wheat fields.", population: 41000000 },
  { code: 'hu', name: 'Hungary', tier: 2, region: 'Europe', category: 'National', fact: "The horizontal tricolor was adopted in 1848.", population: 9700000 },
  { code: 'cz', name: 'Czech Republic', tier: 2, region: 'Europe', category: 'National', fact: "The blue triangle was added to distinguish it from Poland.", population: 10700000 },
  { code: 'sk', name: 'Slovakia', tier: 2, region: 'Europe', category: 'National', fact: "Features a double cross on three mountains.", population: 5400000 },
  { code: 'hr', name: 'Croatia', tier: 2, region: 'Europe', category: 'National', fact: "Features a checkerboard shield called the Šahovnica.", population: 4000000 },
  { code: 'rs', name: 'Serbia', tier: 2, region: 'Europe', category: 'National', fact: "Features a double-headed eagle.", population: 6900000 },
  { code: 'bg', name: 'Bulgaria', tier: 2, region: 'Europe', category: 'National', fact: "The only Slavic flag with green instead of blue.", population: 6900000 },
  { code: 'is', name: 'Iceland', tier: 2, region: 'Europe', category: 'National', fact: "The colors represent fire, ice, and water.", population: 360000 },
  { code: 'ee', name: 'Estonia', tier: 2, region: 'Europe', category: 'National', fact: "The colors represent the sky, soil, and purity.", population: 1300000 },
  { code: 'lv', name: 'Latvia', tier: 2, region: 'Europe', category: 'National', fact: "One of the oldest flags in the world.", population: 1900000 },
  { code: 'lt', name: 'Lithuania', tier: 2, region: 'Europe', category: 'National', fact: "Yellow represents the sun, green represents forests.", population: 2800000 },
  { code: 'bt', name: 'Bhutan', tier: 4, region: 'Asia', category: 'National', fact: "Features the Thunder Dragon, Druk.", population: 770000 },
  { code: 'np', name: 'Nepal', tier: 4, region: 'Asia', category: 'National', fact: "The only non-quadrilateral national flag.", population: 29000000 },
  { code: 'ro', name: 'Romania', tier: 2, region: 'Europe', category: 'National', fact: "The tricolor is identical to Chad's flag.", population: 19000000 },

  // US States
  { code: 'us-al', name: 'Alabama', tier: 3, region: 'Americas', category: 'US-State', fact: "Features a red saltire on a white field." },
  { code: 'us-ak', name: 'Alaska', tier: 3, region: 'Americas', category: 'US-State', fact: "Features the Big Dipper and the North Star." },
  { code: 'us-az', name: 'Arizona', tier: 3, region: 'Americas', category: 'US-State', fact: "Features a copper star and rays of the setting sun." },
  { code: 'us-ar', name: 'Arkansas', tier: 3, region: 'Americas', category: 'US-State', fact: "Features a diamond shape representing its diamond mines." },
  { code: 'us-ca', name: 'California', tier: 2, region: 'Americas', category: 'US-State', fact: "Features a grizzly bear." },
  { code: 'us-co', name: 'Colorado', tier: 3, region: 'Americas', category: 'US-State', fact: "Features a red 'C' with a gold disk inside." },
  { code: 'us-ct', name: 'Connecticut', tier: 3, region: 'Americas', category: 'US-State', fact: "Features three grapevines." },
  { code: 'us-de', name: 'Delaware', tier: 3, region: 'Americas', category: 'US-State', fact: "Features the date of its ratification of the Constitution." },
  { code: 'us-fl', name: 'Florida', tier: 2, region: 'Americas', category: 'US-State', fact: "Features a red saltire on a white field." },
  { code: 'us-ga', name: 'Georgia', tier: 3, region: 'Americas', category: 'US-State', fact: "Features the state seal and 13 stars." },
  { code: 'us-hi', name: 'Hawaii', tier: 3, region: 'Americas', category: 'US-State', fact: "The only US state flag to feature the Union Jack." },
  { code: 'us-id', name: 'Idaho', tier: 3, region: 'Americas', category: 'US-State', fact: "Features the state seal on a blue field." },
  { code: 'us-il', name: 'Illinois', tier: 3, region: 'Americas', category: 'US-State', fact: "Features an eagle and the state seal." },
  { code: 'us-in', name: 'Indiana', tier: 3, region: 'Americas', category: 'US-State', fact: "Features a torch and 19 stars." },
  { code: 'us-ia', name: 'Iowa', tier: 3, region: 'Americas', category: 'US-State', fact: "Features a vertical tricolor with an eagle." },
  { code: 'us-ks', name: 'Kansas', tier: 3, region: 'Americas', category: 'US-State', fact: "Features the state seal and a sunflower." },
  { code: 'us-ky', name: 'Kentucky', tier: 3, region: 'Americas', category: 'US-State', fact: "Features the state seal with two men embracing." },
  { code: 'us-la', name: 'Louisiana', tier: 3, region: 'Americas', category: 'US-State', fact: "Features a pelican feeding its young." },
  { code: 'us-me', name: 'Maine', tier: 3, region: 'Americas', category: 'US-State', fact: "Features the state coat of arms." },
  { code: 'us-md', name: 'Maryland', tier: 3, region: 'Americas', category: 'US-State', fact: "Features the heraldic banner of George Calvert." },
  { code: 'us-ma', name: 'Massachusetts', tier: 3, region: 'Americas', category: 'US-State', fact: "Features a Native American with a bow and arrow." },
  { code: 'us-mi', name: 'Michigan', tier: 3, region: 'Americas', category: 'US-State', fact: "Features the state coat of arms with an elk and moose." },
  { code: 'us-mn', name: 'Minnesota', tier: 3, region: 'Americas', category: 'US-State', fact: "Recently redesigned to feature a North Star." },
  { code: 'us-ms', name: 'Mississippi', tier: 3, region: 'Americas', category: 'US-State', fact: "Features a magnolia blossom." },
  { code: 'us-mo', name: 'Missouri', tier: 3, region: 'Americas', category: 'US-State', fact: "Features a horizontal tricolor with the state seal." },
  { code: 'us-mt', name: 'Montana', tier: 3, region: 'Americas', category: 'US-State', fact: "Features the state seal on a blue field." },
  { code: 'us-ne', name: 'Nebraska', tier: 3, region: 'Americas', category: 'US-State', fact: "Features the state seal on a blue field." },
  { code: 'us-nv', name: 'Nevada', tier: 3, region: 'Americas', category: 'US-State', fact: "Features a silver star and sagebrush." },
  { code: 'us-nh', name: 'New Hampshire', tier: 3, region: 'Americas', category: 'US-State', fact: "Features the state seal showing a ship." },
  { code: 'us-nj', name: 'New Jersey', tier: 3, region: 'Americas', category: 'US-State', fact: "Features the state coat of arms on a buff field." },
  { code: 'us-nm', name: 'New Mexico', tier: 3, region: 'Americas', category: 'US-State', fact: "Features the Zia sun symbol." },
  { code: 'us-ny', name: 'New York', tier: 2, region: 'Americas', category: 'US-State', fact: "Features the state coat of arms." },
  { code: 'us-nc', name: 'North Carolina', tier: 3, region: 'Americas', category: 'US-State', fact: "Features a blue union with two dates." },
  { code: 'us-nd', name: 'North Dakota', tier: 3, region: 'Americas', category: 'US-State', fact: "Features an eagle similar to the US coat of arms." },
  { code: 'us-oh', name: 'Ohio', tier: 3, region: 'Americas', category: 'US-State', fact: "The only non-rectangular US state flag." },
  { code: 'us-ok', name: 'Oklahoma', tier: 3, region: 'Americas', category: 'US-State', fact: "Features an Osage warrior's shield." },
  { code: 'us-or', name: 'Oregon', tier: 3, region: 'Americas', category: 'US-State', fact: "The only US state flag with different designs on each side." },
  { code: 'us-pa', name: 'Pennsylvania', tier: 3, region: 'Americas', category: 'US-State', fact: "Features the state coat of arms with two horses." },
  { code: 'us-ri', name: 'Rhode Island', tier: 3, region: 'Americas', category: 'US-State', fact: "Features a gold anchor and 13 stars." },
  { code: 'us-sc', name: 'South Carolina', tier: 3, region: 'Americas', category: 'US-State', fact: "Features a palmetto tree and a crescent." },
  { code: 'us-sd', name: 'South Dakota', tier: 3, region: 'Americas', category: 'US-State', fact: "Features the state seal surrounded by a sun." },
  { code: 'us-tn', name: 'Tennessee', tier: 3, region: 'Americas', category: 'US-State', fact: "Features three stars representing the three grand divisions." },
  { code: 'us-tx', name: 'Texas', tier: 2, region: 'Americas', category: 'US-State', fact: "Known as the Lone Star flag." },
  { code: 'us-ut', name: 'Utah', tier: 3, region: 'Americas', category: 'US-State', fact: "Features a beehive representing industry." },
  { code: 'us-vt', name: 'Vermont', tier: 3, region: 'Americas', category: 'US-State', fact: "Features the state coat of arms." },
  { code: 'us-va', name: 'Virginia', tier: 3, region: 'Americas', category: 'US-State', fact: "Features the state seal showing 'Virtus' defeating 'Tyranny'." },
  { code: 'us-wa', name: 'Washington', tier: 3, region: 'Americas', category: 'US-State', fact: "The only US state flag with a green field and a portrait." },
  { code: 'us-wv', name: 'West Virginia', tier: 3, region: 'Americas', category: 'US-State', fact: "Features the state coat of arms on a white field." },
  { code: 'us-wi', name: 'Wisconsin', tier: 3, region: 'Americas', category: 'US-State', fact: "Features the state coat of arms." },
  { code: 'us-wy', name: 'Wyoming', tier: 3, region: 'Americas', category: 'US-State', fact: "Features a silhouette of an American bison." },

  // Indian States
  { code: 'in-ka', name: 'Karnataka', tier: 3, region: 'Asia', category: 'India-State', fact: "Unofficial flag is yellow and red." },
  { code: 'in-tn', name: 'Tamil Nadu', tier: 3, region: 'Asia', category: 'India-State', fact: "State emblem features a temple tower." },
  { code: 'in-mh', name: 'Maharashtra', tier: 3, region: 'Asia', category: 'India-State', fact: "Home to Mumbai, the financial capital of India." },
  { code: 'in-up', name: 'Uttar Pradesh', tier: 3, region: 'Asia', category: 'India-State', fact: "The most populous state in India." },
  { code: 'in-wb', name: 'West Bengal', tier: 3, region: 'Asia', category: 'India-State', fact: "Known for its rich cultural heritage and literature." },
  { code: 'in-gj', name: 'Gujarat', tier: 3, region: 'Asia', category: 'India-State', fact: "Birthplace of Mahatma Gandhi." },
  { code: 'in-rj', name: 'Rajasthan', tier: 3, region: 'Asia', category: 'India-State', fact: "The largest state in India by area." },
  { code: 'in-kl', name: 'Kerala', tier: 3, region: 'Asia', category: 'India-State', fact: "Known as 'God's Own Country'." },
  { code: 'in-pb', name: 'Punjab', tier: 3, region: 'Asia', category: 'India-State', fact: "The breadbasket of India." },
  { code: 'in-ap', name: 'Andhra Pradesh', tier: 3, region: 'Asia', category: 'India-State', fact: "Known for its rich history and temples." },
  { code: 'in-tg', name: 'Telangana', tier: 3, region: 'Asia', category: 'India-State', fact: "India's youngest state, formed in 2014." },
  { code: 'in-mp', name: 'Madhya Pradesh', tier: 3, region: 'Asia', category: 'India-State', fact: "Known as the 'Heart of India'." },
  { code: 'in-br', name: 'Bihar', tier: 3, region: 'Asia', category: 'India-State', fact: "The birthplace of Buddhism and Jainism." },

  // Danish Kommune (Expanded)
  // ... (keeping existing ones)
  { code: 'dk-cph', name: 'Copenhagen', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Features the city's coat of arms." },
  { code: 'dk-aar', name: 'Aarhus', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Denmark's second-largest city." },
  { code: 'dk-odn', name: 'Odense', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Birthplace of Hans Christian Andersen." },
  { code: 'dk-aal', name: 'Aalborg', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Known for its waterfront and architecture." },
  { code: 'dk-esb', name: 'Esbjerg', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "A major North Sea port." },
  { code: 'dk-ran', name: 'Randers', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Known for its tropical zoo, Randers Regnskov." },
  { code: 'dk-kol', name: 'Kolding', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Home to the Koldinghus royal castle." },
  { code: 'dk-hor', name: 'Horsens', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Known for its cultural festivals." },
  { code: 'dk-vej', name: 'Vejle', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Located at the head of Vejle Fjord." },
  { code: 'dk-ros', name: 'Roskilde', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Famous for its cathedral and music festival." },
  { code: 'dk-fre', name: 'Frederiksberg', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "An enclave within Copenhagen." },
  { code: 'dk-hel', name: 'Helsingør', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Home to Kronborg Castle (Hamlet's castle)." },
  { code: 'dk-her', name: 'Herning', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "A center for textile industry and trade fairs." },
  { code: 'dk-sil', name: 'Silkeborg', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Surrounded by forests and lakes." },
  { code: 'dk-nae', name: 'Næstved', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "One of the oldest towns in Denmark." },
  { code: 'dk-vib', name: 'Viborg', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "One of the oldest cities in Denmark, once the capital of Jutland." },
  { code: 'dk-hol', name: 'Holstebro', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Known for its rich cultural life and sculptures." },
  { code: 'dk-sla', name: 'Slagelse', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Home to the Trelleborg viking fortress." },
  { code: 'dk-son', name: 'Sønderborg', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Located on the island of Als, near the German border." },
  { code: 'dk-hjo', name: 'Hjørring', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "The main town of Vendsyssel." },
  { code: 'dk-holb', name: 'Holbæk', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Located on the Isefjord." },
  { code: 'dk-gul', name: 'Guldborgsund', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Covers the islands of Falster and eastern Lolland." },
  { code: 'dk-freh', name: 'Frederikshavn', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "A major ferry port connecting to Norway and Sweden." },
  { code: 'dk-ave', name: 'Aabenraa', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "A historic port city in Southern Jutland." },
  { code: 'dk-ska', name: 'Skanderborg', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Known for its beautiful lakes and annual music festival." },
  { code: 'dk-rin', name: 'Ringkøbing-Skjern', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "The largest municipality in Denmark by area." },
  { code: 'dk-koe', name: 'Køge', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "A historic market town south of Copenhagen." },
  { code: 'dk-kal', name: 'Kalundborg', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Home to the unique five-towered Church of Our Lady." },
  { code: 'dk-hillerod', name: 'Hillerød', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Home to the magnificent Frederiksborg Castle." },
  { code: 'dk-hvidovre', name: 'Hvidovre', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "A suburb of Copenhagen." },
  { code: 'dk-greve', name: 'Greve', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Known for its long beaches." },
  { code: 'dk-ballerup', name: 'Ballerup', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "A center for business and industry." },
  { code: 'dk-skive', name: 'Skive', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Located on the Limfjord." },
  { code: 'dk-favrskov', name: 'Favrskov', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Located in the heart of Jutland." },
  { code: 'dk-hedensted', name: 'Hedensted', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Located between Horsens and Vejle." },
  { code: 'dk-vordingborg', name: 'Vordingborg', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Home to the Goose Tower, a medieval landmark." },
  { code: 'dk-fredericia', name: 'Fredericia', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "A historic fortress town." },
  { code: 'dk-thisted', name: 'Thisted', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Gateway to the Thy National Park." },
  { code: 'dk-holstebro', name: 'Holstebro', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Known for its rich cultural life and sculptures." },
  { code: 'dk-tarnby', name: 'Tårnby', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Home to Copenhagen Airport." },
  { code: 'dk-bornholm', name: 'Bornholm', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "A rocky island in the Baltic Sea." },
  { code: 'dk-mariagerfjord', name: 'Mariagerfjord', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Located around the Mariager Fjord." },
  { code: 'dk-ikast-brande', name: 'Ikast-Brande', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "A center for the textile industry." },
  { code: 'dk-gribskov', name: 'Gribskov', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Home to the Gribskov forest." },
  { code: 'dk-fredensborg', name: 'Fredensborg', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Home to Fredensborg Palace, a royal residence." },
  { code: 'dk-albertslund', name: 'Albertslund', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Known for its planned urban environment." },
  { code: 'dk-alleroed', name: 'Allerød', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Located in North Zealand." },
  { code: 'dk-assens', name: 'Assens', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "A historic port on the island of Funen." },
  { code: 'dk-billund', name: 'Billund', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Home to the original Legoland." },
  { code: 'dk-broendby', name: 'Brøndby', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Home to Brøndby IF football club." },
  { code: 'dk-broenderslev', name: 'Brønderslev', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Located in North Jutland." },
  { code: 'dk-dragoer', name: 'Dragør', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "A historic fishing village near Copenhagen." },
  { code: 'dk-egedal', name: 'Egedal', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Formed by merging three municipalities in 2007." },
  { code: 'dk-fanoe', name: 'Fanø', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "An island in the Wadden Sea." },
  { code: 'dk-faxe', name: 'Faxe', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Known for its limestone quarry." },
  { code: 'dk-frederikssund', name: 'Frederikssund', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Known for its annual Viking plays." },
  { code: 'dk-furesoe', name: 'Furesø', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Named after the Furesø lake." },
  { code: 'dk-faaborg-midtfyn', name: 'Faaborg-Midtfyn', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Located on the island of Funen." },
  { code: 'dk-gentofte', name: 'Gentofte', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "An affluent suburb of Copenhagen." },
  { code: 'dk-gladsaxe', name: 'Gladsaxe', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "A suburb northwest of Copenhagen." },
  { code: 'dk-glostrup', name: 'Glostrup', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "A major transport hub west of Copenhagen." },
  { code: 'dk-haderslev', name: 'Haderslev', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "A historic cathedral city in Southern Jutland." },
  { code: 'dk-halsnaes', name: 'Halsnæs', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Located on the peninsula between the North Sea and Isefjord." },
  { code: 'dk-herlev', name: 'Herlev', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Home to the Herlev Hospital, Denmark's tallest building." },
  { code: 'dk-hoeje-taastrup', name: 'Høje-Taastrup', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "A major railway junction." },
  { code: 'dk-hoersholm', name: 'Hørsholm', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Home to the Hørsholm Church and Arboretum." },
  { code: 'dk-ishoej', name: 'Ishøj', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Home to the Arken Museum of Modern Art." },
  { code: 'dk-jammerbugt', name: 'Jammerbugt', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Named after the 'Bay of Woe'." },
  { code: 'dk-kerteminde', name: 'Kerteminde', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "A historic port on Funen." },
  { code: 'dk-langeland', name: 'Langeland', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "An island municipality." },
  { code: 'dk-lejre', name: 'Lejre', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "The legendary seat of the first Danish kings." },
  { code: 'dk-lemvig', name: 'Lemvig', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Located on the Limfjord." },
  { code: 'dk-lolland', name: 'Lolland', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "The fourth largest island in Denmark." },
  { code: 'dk-lyngby-taarbaek', name: 'Lyngby-Taarbæk', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Home to the Technical University of Denmark." },
  { code: 'dk-laesoe', name: 'Læsø', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "An island in the Kattegat, known for its salt production." },
  { code: 'dk-middelfart', name: 'Middelfart', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Located at the Little Belt bridge." },
  { code: 'dk-morsoe', name: 'Morsø', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "An island in the Limfjord." },
  { code: 'dk-norddjurs', name: 'Norddjurs', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Located on the Djursland peninsula." },
  { code: 'dk-nordfyns', name: 'Nordfyns', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Located on the northern coast of Funen." },
  { code: 'dk-nyborg', name: 'Nyborg', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Home to Nyborg Castle, Denmark's oldest royal castle." },
  { code: 'dk-odder', name: 'Odder', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Located south of Aarhus." },
  { code: 'dk-odsherred', name: 'Odsherred', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Known for its unique landscape and geopark." },
  { code: 'dk-rebild', name: 'Rebild', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Home to Rebild National Park." },
  { code: 'dk-ringsted', name: 'Ringsted', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "A historic town in the center of Zealand." },
  { code: 'dk-rudersdal', name: 'Rudersdal', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Located north of Copenhagen." },
  { code: 'dk-roedovre', name: 'Rødovre', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "A suburb of Copenhagen." },
  { code: 'dk-samsoe', name: 'Samsø', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "An island known for its renewable energy." },
  { code: 'dk-solroed', name: 'Solrød', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "A coastal municipality south of Copenhagen." },
  { code: 'dk-soroe', name: 'Sorø', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Home to the Sorø Academy." },
  { code: 'dk-stevns', name: 'Stevns', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Famous for the Stevns Klint cliffs." },
  { code: 'dk-struer', name: 'Struer', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Home to Bang & Olufsen." },
  { code: 'dk-svendborg', name: 'Svendborg', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "A maritime center on Funen." },
  { code: 'dk-syddjurs', name: 'Syddjurs', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Home to Mols Bjerge National Park." },
  { code: 'dk-toender', name: 'Tønder', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "A historic town near the German border." },
  { code: 'dk-vallensbaek', name: 'Vallensbæk', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "A coastal suburb of Copenhagen." },
  { code: 'dk-varde', name: 'Varde', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Gateway to the North Sea beaches." },
  { code: 'dk-vejen', name: 'Vejen', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Located in Southern Jutland." },
  { code: 'dk-vesthimmerland', name: 'Vesthimmerland', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "Located in North Jutland." },
  { code: 'dk-aeroe', name: 'Ærø', tier: 3, region: 'Europe', category: 'Danish-Kommune', fact: "An island municipality in the South Funen Archipelago." },

  // Swedish Län (Complete 21)
  { code: 'se-st', name: 'Stockholm', tier: 3, region: 'Europe', category: 'Swedish-Lan', fact: "Features Saint Eric." },
  { code: 'se-vg', name: 'Västra Götaland', tier: 3, region: 'Europe', category: 'Swedish-Lan', fact: "Includes Gothenburg." },
  { code: 'se-sk', name: 'Skåne', tier: 3, region: 'Europe', category: 'Swedish-Lan', fact: "The southernmost province of Sweden." },
  { code: 'se-up', name: 'Uppsala', tier: 3, region: 'Europe', category: 'Swedish-Lan', fact: "Home to the oldest university in Scandinavia." },
  { code: 'se-ab', name: 'Stockholm County', tier: 3, region: 'Europe', category: 'Swedish-Lan', fact: "The most populous county in Sweden." },
  { code: 'se-c', name: 'Uppsala County', tier: 3, region: 'Europe', category: 'Swedish-Lan', fact: "Features a golden lion on a blue field." },
  { code: 'se-d', name: 'Södermanland', tier: 3, region: 'Europe', category: 'Swedish-Lan', fact: "Features a griffin." },
  { code: 'se-e', name: 'Östergötland', tier: 3, region: 'Europe', category: 'Swedish-Lan', fact: "Features a dragon." },
  { code: 'se-f', name: 'Jönköping', tier: 3, region: 'Europe', category: 'Swedish-Lan', fact: "Features a castle." },
  { code: 'se-g', name: 'Kronoberg', tier: 3, region: 'Europe', category: 'Swedish-Lan', fact: "Features a lion with a crossbow." },
  { code: 'se-h', name: 'Kalmar', tier: 3, region: 'Europe', category: 'Swedish-Lan', fact: "Features a lion and a crossbow." },
  { code: 'se-i', name: 'Gotland', tier: 3, region: 'Europe', category: 'Swedish-Lan', fact: "Features a ram." },
  { code: 'se-k', name: 'Blekinge', tier: 3, region: 'Europe', category: 'Swedish-Lan', fact: "Features an oak tree with three crowns." },
  { code: 'se-m', name: 'Skåne County', tier: 3, region: 'Europe', category: 'Swedish-Lan', fact: "Features a griffin's head." },
  { code: 'se-n', name: 'Halland', tier: 3, region: 'Europe', category: 'Swedish-Lan', fact: "Features a silver lion." },
  { code: 'se-o', name: 'Västra Götaland County', tier: 3, region: 'Europe', category: 'Swedish-Lan', fact: "Formed by merging three former counties." },
  { code: 'se-s', name: 'Värmland', tier: 3, region: 'Europe', category: 'Swedish-Lan', fact: "Features an eagle." },
  { code: 'se-t', name: 'Örebro', tier: 3, region: 'Europe', category: 'Swedish-Lan', fact: "Features an eagle and two arrows." },
  { code: 'se-u', name: 'Västmanland', tier: 3, region: 'Europe', category: 'Swedish-Lan', fact: "Features three burning mountains." },
  { code: 'se-w', name: 'Dalarna', tier: 3, region: 'Europe', category: 'Swedish-Lan', fact: "Features two crossed arrows." },
  { code: 'se-x', name: 'Gävleborg', tier: 3, region: 'Europe', category: 'Swedish-Lan', fact: "Features a goat." },
  { code: 'se-y', name: 'Västernorrland', tier: 3, region: 'Europe', category: 'Swedish-Lan', fact: "Features a forest and a river." },
  { code: 'se-z', name: 'Jämtland', tier: 3, region: 'Europe', category: 'Swedish-Lan', fact: "Features an elk." },
  { code: 'se-ac', name: 'Västerbotten', tier: 3, region: 'Europe', category: 'Swedish-Lan', fact: "Features a reindeer." },
  { code: 'se-bd', name: 'Norrbotten', tier: 3, region: 'Europe', category: 'Swedish-Lan', fact: "The northernmost county of Sweden." },

  // German States (Complete 16)
  { code: 'de-be', name: 'Berlin', tier: 2, region: 'Europe', category: 'German-County', fact: "Features a black bear." },
  { code: 'de-by', name: 'Bavaria', tier: 2, region: 'Europe', category: 'German-County', fact: "Features white and blue lozenges." },
  { code: 'de-hh', name: 'Hamburg', tier: 2, region: 'Europe', category: 'German-County', fact: "Features a white castle on a red field." },
  { code: 'de-he', name: 'Hesse', tier: 2, region: 'Europe', category: 'German-County', fact: "Features a striped lion." },
  { code: 'de-bw', name: 'Baden-Württemberg', tier: 2, region: 'Europe', category: 'German-County', fact: "Features three black lions." },
  { code: 'de-br', name: 'Brandenburg', tier: 2, region: 'Europe', category: 'German-County', fact: "Features a red eagle." },
  { code: 'de-hb', name: 'Bremen', tier: 2, region: 'Europe', category: 'German-County', fact: "Features a silver key." },
  { code: 'de-mv', name: 'Mecklenburg-Vorpommern', tier: 2, region: 'Europe', category: 'German-County', fact: "Features a bull's head and a griffin." },
  { code: 'de-ni', name: 'Lower Saxony', tier: 2, region: 'Europe', category: 'German-County', fact: "Features a white horse." },
  { code: 'de-nw', name: 'North Rhine-Westphalia', tier: 2, region: 'Europe', category: 'German-County', fact: "The most populous state in Germany." },
  { code: 'de-rp', name: 'Rhineland-Palatinate', tier: 2, region: 'Europe', category: 'German-County', fact: "Features a lion, a cross, and a wheel." },
  { code: 'de-sl', name: 'Saarland', tier: 2, region: 'Europe', category: 'German-County', fact: "Features four different coats of arms." },
  { code: 'de-sn', name: 'Saxony', tier: 2, region: 'Europe', category: 'German-County', fact: "Features black and gold stripes with a green crown." },
  { code: 'de-st-state', name: 'Saxony-Anhalt', tier: 2, region: 'Europe', category: 'German-County', fact: "Features a bear and an eagle." },
  { code: 'de-sh', name: 'Schleswig-Holstein', tier: 2, region: 'Europe', category: 'German-County', fact: "Features two lions and a nettle leaf." },
  { code: 'de-th-state', name: 'Thuringia', tier: 2, region: 'Europe', category: 'German-County', fact: "Features a striped lion surrounded by eight stars." },

  // Swiss Cantons (Complete 26)
  { code: 'ch-zh', name: 'Zurich', tier: 3, region: 'Europe', category: 'Swiss-Canton', fact: "The flag is divided diagonally into blue and white." },
  { code: 'ch-be', name: 'Bern', tier: 3, region: 'Europe', category: 'Swiss-Canton', fact: "Features a black bear on a red and yellow background." },
  { code: 'ch-ge', name: 'Geneva', tier: 3, region: 'Europe', category: 'Swiss-Canton', fact: "Features an eagle and a key." },
  { code: 'ch-lu', name: 'Lucerne', tier: 3, region: 'Europe', category: 'Swiss-Canton', fact: "Blue and white divided horizontally." },
  { code: 'ch-ur', name: 'Uri', tier: 3, region: 'Europe', category: 'Swiss-Canton', fact: "Features a bull's head." },
  { code: 'ch-sz', name: 'Schwyz', tier: 3, region: 'Europe', category: 'Swiss-Canton', fact: "Features a small white cross on a red field." },
  { code: 'ch-ow', name: 'Obwalden', tier: 3, region: 'Europe', category: 'Swiss-Canton', fact: "Features a silver key on a red and white field." },
  { code: 'ch-nw', name: 'Nidwalden', tier: 3, region: 'Europe', category: 'Swiss-Canton', fact: "Features a double key." },
  { code: 'ch-gl', name: 'Glarus', tier: 3, region: 'Europe', category: 'Swiss-Canton', fact: "Features Saint Fridolin." },
  { code: 'ch-zg', name: 'Zug', tier: 3, region: 'Europe', category: 'Swiss-Canton', fact: "Features a blue horizontal stripe." },
  { code: 'ch-fr', name: 'Fribourg', tier: 3, region: 'Europe', category: 'Swiss-Canton', fact: "Black and white divided horizontally." },
  { code: 'ch-so', name: 'Solothurn', tier: 3, region: 'Europe', category: 'Swiss-Canton', fact: "Red and white divided horizontally." },
  { code: 'ch-bs', name: 'Basel-Stadt', tier: 3, region: 'Europe', category: 'Swiss-Canton', fact: "Features a black bishop's crosier." },
  { code: 'ch-bl', name: 'Basel-Landschaft', tier: 3, region: 'Europe', category: 'Swiss-Canton', fact: "Features a red bishop's crosier." },
  { code: 'ch-sh', name: 'Schaffhausen', tier: 3, region: 'Europe', category: 'Swiss-Canton', fact: "Features a ram." },
  { code: 'ch-ar', name: 'Appenzell Ausserrhoden', tier: 3, region: 'Europe', category: 'Swiss-Canton', fact: "Features a bear and the letters V and R." },
  { code: 'ch-ai', name: 'Appenzell Innerrhoden', tier: 3, region: 'Europe', category: 'Swiss-Canton', fact: "Features a black bear." },
  { code: 'ch-sg', name: 'St. Gallen', tier: 3, region: 'Europe', category: 'Swiss-Canton', fact: "Features a bundle of rods and an axe." },
  { code: 'ch-gr', name: 'Graubünden', tier: 3, region: 'Europe', category: 'Swiss-Canton', fact: "Features an ibex." },
  { code: 'ch-ag', name: 'Aargau', tier: 3, region: 'Europe', category: 'Swiss-Canton', fact: "Features a river and three stars." },
  { code: 'ch-tg', name: 'Thurgau', tier: 3, region: 'Europe', category: 'Swiss-Canton', fact: "Features two golden lions." },
  { code: 'ch-ti', name: 'Ticino', tier: 3, region: 'Europe', category: 'Swiss-Canton', fact: "Red and blue divided horizontally." },
  { code: 'ch-vd', name: 'Vaud', tier: 3, region: 'Europe', category: 'Swiss-Canton', fact: "Features the words 'Liberté et Patrie'." },
  { code: 'ch-vs', name: 'Valais', tier: 3, region: 'Europe', category: 'Swiss-Canton', fact: "Features 13 stars." },
  { code: 'ch-ne', name: 'Neuchâtel', tier: 3, region: 'Europe', category: 'Swiss-Canton', fact: "Green, white, and red tricolor with a small cross." },
  { code: 'ch-ju', name: 'Jura', tier: 3, region: 'Europe', category: 'Swiss-Canton', fact: "Features a crosier and seven stripes." },

  // Commonwealth (Expanded)
  { code: 'ca-on', name: 'Ontario', tier: 3, region: 'Americas', category: 'Commonwealth', fact: "Features the Red Ensign with the Ontario shield." },
  { code: 'ca-qc', name: 'Quebec', tier: 3, region: 'Americas', category: 'Commonwealth', fact: "Features four fleurs-de-lis." },
  { code: 'ca-bc', name: 'British Columbia', tier: 3, region: 'Americas', category: 'Commonwealth', fact: "Features a setting sun and the Union Jack." },
  { code: 'ca-ab', name: 'Alberta', tier: 3, region: 'Americas', category: 'Commonwealth', fact: "Features the provincial shield on a blue field." },
  { code: 'au-nsw', name: 'New South Wales', tier: 3, region: 'Oceania', category: 'Commonwealth', fact: "Features the state badge on a Blue Ensign." },
  { code: 'au-vic', name: 'Victoria', tier: 3, region: 'Oceania', category: 'Commonwealth', fact: "Features the Southern Cross and a crown." },
  { code: 'au-qld', name: 'Queensland', tier: 3, region: 'Oceania', category: 'Commonwealth', fact: "Features a Maltese cross and a crown." },
  { code: 'au-wa', name: 'Western Australia', tier: 3, region: 'Oceania', category: 'Commonwealth', fact: "Features a black swan." },
  { code: 'au-sa', name: 'South Australia', tier: 3, region: 'Oceania', category: 'Commonwealth', fact: "Features a piping shrike." },
  { code: 'au-tas', name: 'Tasmania', tier: 3, region: 'Oceania', category: 'Commonwealth', fact: "Features a red lion." },
  { code: 'ca-ns', name: 'Nova Scotia', tier: 3, region: 'Americas', category: 'Commonwealth', fact: "Features a blue saltire on a white field with the royal arms of Scotland." },

  // World Capitals (Expanded)
  { code: 'cairo', name: 'Cairo', tier: 2, region: 'Africa', category: 'World-Capitals', fact: "Home to the Great Pyramids of Giza.", imageUrl: 'https://picsum.photos/seed/pyramids/800/600' },
  { code: 'sydney', name: 'Sydney', tier: 2, region: 'Oceania', category: 'World-Capitals', fact: "The Opera House is an architectural marvel.", imageUrl: 'https://picsum.photos/seed/sydney/800/600' },
  { code: 'rio', name: 'Rio de Janeiro', tier: 2, region: 'Americas', category: 'World-Capitals', fact: "Christ the Redeemer overlooks the city.", imageUrl: 'https://picsum.photos/seed/rio/800/600' },
  { code: 'london', name: 'London', tier: 1, region: 'Europe', category: 'World-Capitals', fact: "Big Ben is actually the name of the bell.", imageUrl: 'https://picsum.photos/seed/london/800/600' },
  { code: 'paris', name: 'Paris', tier: 1, region: 'Europe', category: 'World-Capitals', fact: "The Eiffel Tower was originally intended to be temporary.", imageUrl: 'https://picsum.photos/seed/paris/800/600' },
  { code: 'tokyo', name: 'Tokyo', tier: 1, region: 'Asia', category: 'World-Capitals', fact: "The most populous metropolitan area in the world.", imageUrl: 'https://picsum.photos/seed/tokyo/800/600' },
  { code: 'washington', name: 'Washington D.C.', tier: 1, region: 'Americas', category: 'World-Capitals', fact: "The White House has 132 rooms.", imageUrl: 'https://picsum.photos/seed/dc/800/600' },
  { code: 'berlin', name: 'Berlin', tier: 1, region: 'Europe', category: 'World-Capitals', fact: "The Brandenburg Gate is a symbol of unity.", imageUrl: 'https://picsum.photos/seed/berlin/800/600' },
  { code: 'rome', name: 'Rome', tier: 1, region: 'Europe', category: 'World-Capitals', fact: "The Colosseum could hold up to 80,000 spectators.", imageUrl: 'https://picsum.photos/seed/rome/800/600' },
  { code: 'madrid', name: 'Madrid', tier: 1, region: 'Europe', category: 'World-Capitals', fact: "Home to the Royal Palace, the largest in Europe.", imageUrl: 'https://picsum.photos/seed/madrid/800/600' },
  { code: 'ottawa', name: 'Ottawa', tier: 2, region: 'Americas', category: 'World-Capitals', fact: "The Rideau Canal becomes the world's largest skating rink.", imageUrl: 'https://picsum.photos/seed/ottawa/800/600' },
  { code: 'canberra', name: 'Canberra', tier: 2, region: 'Oceania', category: 'World-Capitals', fact: "A planned city designed by American architects.", imageUrl: 'https://picsum.photos/seed/canberra/800/600' },
  { code: 'delhi', name: 'New Delhi', tier: 2, region: 'Asia', category: 'World-Capitals', fact: "Features the India Gate war memorial.", imageUrl: 'https://picsum.photos/seed/delhi/800/600' },
  { code: 'beijing', name: 'Beijing', tier: 1, region: 'Asia', category: 'World-Capitals', fact: "Home to the Forbidden City.", imageUrl: 'https://picsum.photos/seed/beijing/800/600' },
  { code: 'seoul', name: 'Seoul', tier: 1, region: 'Asia', category: 'World-Capitals', fact: "A leading global technology hub.", imageUrl: 'https://picsum.photos/seed/seoul/800/600' },
  { code: 'moscow', name: 'Moscow', tier: 1, region: 'Europe', category: 'World-Capitals', fact: "Features the Red Square and the Kremlin.", imageUrl: 'https://picsum.photos/seed/moscow/800/600' },
  { code: 'bangkok', name: 'Bangkok', tier: 2, region: 'Asia', category: 'World-Capitals', fact: "Known for its vibrant street life and ornate shrines.", imageUrl: 'https://picsum.photos/seed/bangkok/800/600' },
  { code: 'vienna', name: 'Vienna', tier: 2, region: 'Europe', category: 'World-Capitals', fact: "Known as the City of Music.", imageUrl: 'https://picsum.photos/seed/vienna/800/600' },
  { code: 'athens', name: 'Athens', tier: 2, region: 'Europe', category: 'World-Capitals', fact: "The birthplace of democracy.", imageUrl: 'https://picsum.photos/seed/athens/800/600' },
  { code: 'lisbon', name: 'Lisbon', tier: 2, region: 'Europe', category: 'World-Capitals', fact: "One of the oldest cities in the world.", imageUrl: 'https://picsum.photos/seed/lisbon/800/600' },
  { code: 'mexico-city', name: 'Mexico City', tier: 2, region: 'Americas', category: 'World-Capitals', fact: "Built on the ruins of the Aztec capital Tenochtitlan.", imageUrl: 'https://picsum.photos/seed/mexicocity/800/600' },

  // Language Guess (Expanded)
  { code: 'en', name: 'English', tier: 1, region: 'Global', category: 'Language-Guess', fact: "English is the most spoken language in the world by total speakers.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/5e/En-us-English.ogg' },
  { code: 'es-lang', name: 'Spanish', tier: 1, region: 'Americas', category: 'Language-Guess', fact: "Spanish is the second most spoken native language.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Es-Spanish.ogg' },
  { code: 'fr-lang', name: 'French', tier: 1, region: 'Europe', category: 'Language-Guess', fact: "French is an official language in 29 countries.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a1/Fr-French.ogg' },
  { code: 'de-lang', name: 'German', tier: 1, region: 'Europe', category: 'Language-Guess', fact: "German is the most widely spoken native language in the EU.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d3/De-German.ogg' },
  { code: 'hi-lang', name: 'Hindi', tier: 2, region: 'Asia', category: 'Language-Guess', fact: "Hindi is written in the Devanagari script.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b2/Hi-Hindi.ogg' },
  { code: 'it-lang', name: 'Italian', tier: 1, region: 'Europe', category: 'Language-Guess', fact: "Italian is the language of music and opera.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/3d/It-Italiano.ogg' },
  { code: 'pt-lang', name: 'Portuguese', tier: 1, region: 'Europe', category: 'Language-Guess', fact: "Portuguese is spoken by over 250 million people.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1e/Pt-Portugu%C3%AAs.ogg' },
  { code: 'sv-lang', name: 'Swedish', tier: 2, region: 'Europe', category: 'Language-Guess', fact: "Swedish is a North Germanic language.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Sv-Svenska.ogg' },
  { code: 'ja-lang', name: 'Japanese', tier: 2, region: 'Asia', category: 'Language-Guess', fact: "Japanese uses three different writing systems.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Ja-Nihongo.ogg' },
  { code: 'zh-lang', name: 'Chinese', tier: 2, region: 'Asia', category: 'Language-Guess', fact: "Mandarin Chinese is the most spoken native language.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Zh-Zhongwen.ogg' },
  { code: 'ru-lang', name: 'Russian', tier: 2, region: 'Europe', category: 'Language-Guess', fact: "Russian uses the Cyrillic alphabet.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/10/Ru-Russkiy_yazyk.ogg' },
  { code: 'ar-lang', name: 'Arabic', tier: 2, region: 'Africa', category: 'Language-Guess', fact: "Arabic is written from right to left.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/c0/Ar-Al-arabiyyah.ogg' },
  { code: 'ko-lang', name: 'Korean', tier: 2, region: 'Asia', category: 'Language-Guess', fact: "Korean uses the Hangul alphabet.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/0d/Ko-Hangugeo.ogg' },
  { code: 'nl-lang', name: 'Dutch', tier: 2, region: 'Europe', category: 'Language-Guess', fact: "Dutch is closely related to both German and English.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/97/Nl-Nederlands.ogg' },
  { code: 'el-lang', name: 'Greek', tier: 2, region: 'Europe', category: 'Language-Guess', fact: "Greek has one of the longest documented histories.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/c3/El-Ellinika.ogg' },
  { code: 'tr-lang', name: 'Turkish', tier: 2, region: 'Asia', category: 'Language-Guess', fact: "Turkish was written in Arabic script until 1928.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b0/Tr-T%C3%BCrk%C3%A7e.ogg' },
  { code: 'vi-lang', name: 'Vietnamese', tier: 2, region: 'Asia', category: 'Language-Guess', fact: "Vietnamese is a tonal language.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e4/Vi-Ti%E1%BA%BFng_Vi%E1%BB%87t.ogg' },
  { code: 'th-lang', name: 'Thai', tier: 2, region: 'Asia', category: 'Language-Guess', fact: "Thai has its own unique script.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d4/Th-Phasa_Thai.ogg' },
  { code: 'pl-lang', name: 'Polish', tier: 2, region: 'Europe', category: 'Language-Guess', fact: "Polish is known for its complex consonant clusters.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d1/Pl-J%C4%99zyk_polski.ogg' },
  { code: 'he-lang', name: 'Hebrew', tier: 2, region: 'Asia', category: 'Language-Guess', fact: "Hebrew was revived as a spoken language in the 19th century.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/c0/He-Ivrit.ogg' },
  { code: 'da-lang', name: 'Danish', tier: 2, region: 'Europe', category: 'Language-Guess', fact: "Danish has a unique sound called 'stød'.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d4/Da-Dansk.ogg' },
  { code: 'fi-lang', name: 'Finnish', tier: 2, region: 'Europe', category: 'Language-Guess', fact: "Finnish is not related to the Scandinavian languages.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Fi-Suomi.ogg' },
  { code: 'no-lang', name: 'Norwegian', tier: 2, region: 'Europe', category: 'Language-Guess', fact: "Norwegian has two official written forms.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/0b/No-Norsk.ogg' },
  { code: 'is-lang', name: 'Icelandic', tier: 3, region: 'Europe', category: 'Language-Guess', fact: "Icelandic has changed very little since the Viking Age.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Is-%C3%8Dslenska.ogg' },
  { code: 'et-lang', name: 'Estonian', tier: 3, region: 'Europe', category: 'Language-Guess', fact: "Estonian is closely related to Finnish.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/0d/Et-Eesti_keel.ogg' },
  { code: 'lv-lang', name: 'Latvian', tier: 3, region: 'Europe', category: 'Language-Guess', fact: "Latvian is one of the two surviving Baltic languages.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b3/Lv-Latvie%C5%A1u_valoda.ogg' },
  { code: 'lt-lang', name: 'Lithuanian', tier: 3, region: 'Europe', category: 'Language-Guess', fact: "Lithuanian is considered one of the most archaic Indo-European languages.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1e/Lt-Lietuvi%C5%B3_kalba.ogg' },
  { code: 'ro-lang', name: 'Romanian', tier: 2, region: 'Europe', category: 'Language-Guess', fact: "Romanian is a Romance language like Italian and French.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b9/Ro-Rom%C3%A2n%C4%83.ogg' },
  { code: 'hu-lang', name: 'Hungarian', tier: 3, region: 'Europe', category: 'Language-Guess', fact: "Hungarian is not an Indo-European language.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Hu-Magyar.ogg' },
  { code: 'cs-lang', name: 'Czech', tier: 2, region: 'Europe', category: 'Language-Guess', fact: "Czech is famous for the sound 'ř'.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/8c/Cs-%C4%8Ce%C5%A1tina.ogg' },
  { code: 'sk-lang', name: 'Slovak', tier: 2, region: 'Europe', category: 'Language-Guess', fact: "Slovak is often called 'the Esperanto of Slavic languages'.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Sk-Sloven%C4%8Dina.ogg' },
  { code: 'hr-lang', name: 'Croatian', tier: 2, region: 'Europe', category: 'Language-Guess', fact: "Croatian uses the Latin alphabet with special characters.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Hr-Hrvatski.ogg' },
  { code: 'sr-lang', name: 'Serbian', tier: 2, region: 'Europe', category: 'Language-Guess', fact: "Serbian can be written in both Cyrillic and Latin scripts.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Sr-Srpski.ogg' },
  { code: 'bg-lang', name: 'Bulgarian', tier: 2, region: 'Europe', category: 'Language-Guess', fact: "Bulgarian was the first Slavic language to be written.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Bg-B%C4%83lgarski.ogg' },
  { code: 'sq-lang', name: 'Albanian', tier: 3, region: 'Europe', category: 'Language-Guess', fact: "Albanian is an independent branch of the Indo-European family.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4d/Sq-Shqip.ogg' },
  { code: 'hy-lang', name: 'Armenian', tier: 3, region: 'Asia', category: 'Language-Guess', fact: "Armenian has its own unique alphabet.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Hy-Hayeren.ogg' },
  { code: 'ka-lang', name: 'Georgian', tier: 3, region: 'Asia', category: 'Language-Guess', fact: "Georgian has its own unique script called Mkhedruli.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Ka-Kartuli.ogg' },
  { code: 'az-lang', name: 'Azerbaijani', tier: 3, region: 'Asia', category: 'Language-Guess', fact: "Azerbaijani is a Turkic language.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Az-Az%C9%99rbaycan_dili.ogg' },
  { code: 'kk-lang', name: 'Kazakh', tier: 3, region: 'Asia', category: 'Language-Guess', fact: "Kazakh is a Turkic language written in Cyrillic.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Kk-Qazaq_tili.ogg' },
  { code: 'uz-lang', name: 'Uzbek', tier: 3, region: 'Asia', category: 'Language-Guess', fact: "Uzbek is the most spoken Turkic language in Central Asia.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Uz-O%CA%BBzbek_tili.ogg' },
  { code: 'tk-lang', name: 'Turkmen', tier: 3, region: 'Asia', category: 'Language-Guess', fact: "Turkmen is the official language of Turkmenistan.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Tk-T%C3%BCrkmen_dili.ogg' },
  { code: 'ky-lang', name: 'Kyrgyz', tier: 3, region: 'Asia', category: 'Language-Guess', fact: "Kyrgyz is closely related to Kazakh.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Ky-Kyrgyz_tili.ogg' },
  { code: 'tg-lang', name: 'Tajik', tier: 3, region: 'Asia', category: 'Language-Guess', fact: "Tajik is a variety of Persian.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Tg-Tojiki.ogg' },
  { code: 'mn-lang', name: 'Mongolian', tier: 3, region: 'Asia', category: 'Language-Guess', fact: "Mongolian uses the Cyrillic alphabet in Mongolia.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Mn-Mongol_khel.ogg' },
  { code: 'km-lang', name: 'Khmer', tier: 3, region: 'Asia', category: 'Language-Guess', fact: "Khmer has the largest alphabet in the world.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Km-Khmer.ogg' },
  { code: 'lo-lang', name: 'Lao', tier: 3, region: 'Asia', category: 'Language-Guess', fact: "Lao is closely related to Thai.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Lo-Phasa_Lao.ogg' },
  { code: 'my-lang', name: 'Burmese', tier: 3, region: 'Asia', category: 'Language-Guess', fact: "Burmese is a tonal language.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/My-Myanmar_bhasa.ogg' },
  { code: 'ms-lang', name: 'Malay', tier: 2, region: 'Asia', category: 'Language-Guess', fact: "Malay is the basis for modern Indonesian.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Ms-Bahasa_Melayu.ogg' },
  { code: 'id-lang', name: 'Indonesian', tier: 2, region: 'Asia', category: 'Language-Guess', fact: "Indonesian was created as a lingua franca.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Id-Bahasa_Indonesia.ogg' },
  { code: 'tl-lang', name: 'Tagalog', tier: 2, region: 'Asia', category: 'Language-Guess', fact: "Tagalog is the basis for the Filipino national language.", audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Tl-Tagalog.ogg' },
];
